name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v4

      - name: Configurar cache de Node.js
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm ci

      - name: Build
        run: npm run build

      - name: Trigger Test Workflow
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test.yml'
            });
            console.log(`Triggered Test Workflow. Status: ${response.status}`);