name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v4

      - name: Setar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm ci

      - name: Deploy para Produção
        run: npm run deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          OTHER_ENV_VAR: ${{ secrets.OTHER_ENV_VAR }}