name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: simpatech

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - name: Checar o código
        uses: actions/checkout@v4

      - name: Configurar cache de Node.js
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm ci

      - name: Aguarde até que o MySQL esteja pronto
        run: |
          for i in {30..0}; do
            if mysqladmin ping -h127.0.0.1 -uroot -p${{ secrets.DB_PASSWORD }} &> /dev/null; then
              break
            fi
            echo 'MySQL ainda não está pronto, dormindo...'
            sleep 1
          done

      - name: Criar tabelas do banco de dados
        run: npm run typeorm migration:run

      - name: Executar Testes de Unidade
        run: npm run test

      - name: Executar Testes de Integração
        run: npm run test:integration

      - name: Análise de Segurança
        uses: snyk/actions/node@v2
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}